version: '3.8'

services:
    node:
        image: node:latest
        container_name: node
        ports:
            - "3008:4000"
        volumes:
            - ./:/var/www/
            - node_modules:/var/www/node_modules
        working_dir: /var/www/
        command: sh -c "npm install && node index.js"
        restart: on-failure
        networks:
            - web_traffic

    worker:
        image: node:latest
        container_name: worker
        volumes:
            - ./:/var/www/
            - node_modules:/var/www/node_modules
        working_dir: /var/www/
        command: sh -c "npm install && node ./src/worker/index.js"
        restart: on-failure
        depends_on:
          - node
        networks:
            - web_traffic

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "127.0.0.1:6379:6379"
        restart: on-failure
        networks:
            - web_traffic

volumes:
    node_modules:
